export type Ticker = {
  symbol: string;
  last: number;
  change_24h: number;
  volume_24h: number;
  high_24h: number;
  low_24h: number;
  timestamp: string;
  trend?: string;
  trend_score?: number;
  rsi?: number;
  signal?: "BUY" | "SELL" | "HOLD" | "NO_TRADE";
  confidence?: number;
};

export type Signal = {
  id?: string;
  symbol: string;
  signal: "BUY" | "SELL" | "HOLD" | "NO_TRADE";
  action?: "BUY" | "SELL" | "HOLD" | "NO_TRADE";
  score: number;
  confidence: number;
  explanation: string[];
  expected_move: string;
  expected_window: string;
  expected_time?: string;
  risk: "Low" | "Medium" | "High" | "LOW_RISK" | "MEDIUM_RISK" | "HIGH_RISK" | "NO_TRADE";
  entry?: number;
  target?: number;
  stop_loss?: number;
  expected_profit?: number;
  expected_duration_hours?: number | string;
  target_eta?: string;
  estimated_target_time?: string;
  probability_of_success?: number;
  entry_zone?: string | { low?: number; high?: number; min?: number; max?: number; from?: number; to?: number };
  entry_zone_low?: number;
  entry_zone_high?: number;
  buy_back_level_1?: number;
  buy_back_level_2?: number;
  buy_back_level_3?: number;
  buy_back_window?: string;
  buy_back_eta?: string;
  re_entry_zone?: string | { low?: number; high?: number; min?: number; max?: number; from?: number; to?: number };
  re_entry_window?: string;
  forecast_timeline?: unknown[];
  price_forecast_timeline?: unknown[];
  risk_reward?: string;
  decision?: {
    status: "TRADE" | "NO_TRADE";
    signal_type?: "BUY" | "SELL" | "HOLD";
    confidence_score: number;
    probability_of_success?: number;
    entry_price?: number;
    current_price?: number;
    take_profit_1?: number;
    take_profit_2?: number;
    take_profit_3?: number;
    stop_loss?: number;
    estimated_duration?: string;
    expected_duration_hours?: number | string;
    target_eta?: string;
    estimated_target_time?: string;
    net_profit_percent?: number;
    gross_profit_percent?: number;
    risk_reward_ratio?: string;
    validation_passed?: boolean;
    reason?: string;
    buy_back_level_1?: number;
    buy_back_level_2?: number;
    buy_back_level_3?: number;
    buy_back_window?: string;
    buy_back_eta?: string;
    re_entry_zone?: string | { low?: number; high?: number; min?: number; max?: number; from?: number; to?: number };
    re_entry_window?: string;
    forecast_timeline?: unknown[];
    price_forecast_timeline?: unknown[];
  };
  created_at?: string;
};

export type Prediction = {
  id?: string;
  symbol: string;
  timeframe: string;
  direction?: "UP" | "DOWN" | "SIDEWAYS" | "BUY" | "SELL" | "HOLD" | string;
  confidence?: number;
  source_timestamp?: string;
  source_close?: number;
  current_price?: number;
  predicted_price?: number;
  predicted_change_pct?: number;
  predicted_return_pct?: number;
  predicted_high?: number;
  predicted_low?: number;
  predicted_direction?: string;
  prediction_timestamp?: string;
  target_timestamp?: string;
  probability_plus_2pct?: number;
  probability_plus_5pct?: number;
  probability_plus_10pct?: number;
  probability_stop_loss?: number;
  probability_target1?: number;
  probability_target2?: number;
  probability_target3?: number;
  market_regime?: string;
  market_regime_score?: number;
  regime_confidence?: number;
  historical_win_rate?: number;
  historical_avg_return?: number;
  historical_max_return?: number;
  historical_avg_drawdown?: number;
  similarity_score?: number;
  pattern_confidence?: number;
  expected_peak_price?: number;
  expected_peak_time?: string;
  expected_peak_return_pct?: number;
  peak_probability?: number;
  expected_pullback_price?: number;
  expected_pullback_time?: string;
  pullback_probability?: number;
  expected_reentry_price?: number;
  expected_reentry_time?: string;
  expected_drawdown_pct?: number;
  holding_duration?: string;
  recommended_action?: string;
  action_confidence?: number;
  confidence_score?: number;
  opportunity_score_v2?: number;
  buy_score?: number;
  sell_score?: number;
  reentry_score?: number;
  overall_opportunity_score?: number;
  expected_move?: string;
  opportunity_score?: number;
  entry_zone?: string | number[] | { low?: number; high?: number; min?: number; max?: number; from?: number; to?: number };
  stop_loss?: number;
  targets?: number[];
  take_profit_1?: number;
  take_profit_2?: number;
  take_profit_3?: number;
  risk_reward_ratio?: string;
  exit_strategy?: string;
  reentry_strategy?: string;
  reasoning?: string[];
  probabilities?: Record<string, number>;
  validation_accuracy?: number;
  model_warning?: string;
  created_at?: string;
  updated_at?: string;
};

export type Candle = { timestamp: string; open: number; high: number; low: number; close: number; volume: number };
